enum CronJobs {
  BANK_ACCOUNT_STATUS_STRIPE = 'BANK_ACCOUNT_STATUS_STRIPE',
  TRANSACTION_CHARGE_STATUS_STRIPE = 'TRANSACTION_CHARGE_STATUS_STRIPE',
  TRANSACTION_TRANSFER_STATUS_STRIPE = 'TRANSACTION_TRANSFER_STATUS_STRIPE',
}

export { CronJobs };
