language: node_js
node_js:
  - 12.16.2

branches:
  only:
    - master
    - develop

jobs:
  include:
    # DEVELOP
    - stage: Backend (STAGING)
      if: branch = develop
      install:
        - cd petromiles-backend
        - npm install
      script:
        - npm run test
        - npm run test:cov
        - npm run build
      deploy:
        provider: heroku
        api_key: $HEROKU_APIKEY
        app: $HEROKU_BE_STAGING
        skip_cleanup: true
        on:
          repo: gustavosr98/petromiles
          branch: develop

    - stage: Frontend (STAGING)
      if: branch = develop
      install:
        - cd petromiles-frontend
        - npm install
      script:
        - npm run test
        - npm run build
      deploy:
        provider: heroku
        api_key: $HEROKU_APIKEY
        app: $HEROKU_FE_STAGING
        skip_cleanup: true
        on:
          repo: gustavosr98/petromiles
          branch: develop

    # MASTER
    - stage: Backend (PEPRO)
      if: branch = master
      install:
        - cd petromiles-backend
        - npm install
      script:
        - npm run test
        - npm run test:cov
        - npm run build
      deploy:
        provider: heroku
        api_key: $HEROKU_APIKEY
        app: $HEROKU_BE_PREPRO
        skip_cleanup: true
        on:
          repo: gustavosr98/petromiles
          branch: master

    - stage: Frontend (PEPRO)
      if: branch = develop
      install:
        - cd petromiles-frontend
        - npm install
      script:
        - npm run test
        - npm run build
      deploy:
        provider: heroku
        api_key: $HEROKU_APIKEY
        app: $HEROKU_FE_PEPRO
        skip_cleanup: true
        on:
          repo: gustavosr98/petromiles
          branch: master
