language: node_js
node_js:
  - 12.16.2
branches:
  only:
    - master
    - develop
    - FASE3-028
jobs:
  include:
    - name: Backend | NestJS
      install:
        - cd petromiles-backend
        - npm install
      script:
        - npm run test
        - npm run test:e2e
        - npm run build
        # Coveralls.io
        # - npm run test:cov
      deploy:
        provider: heroku
        api_key: $HEROKU_APIKEY
        app:
          FASE3-028: staging-petromiles-backend
          develop: staging-petromiles-backend
          master: prepro-petromiles-backend
        on:
          repo: ingswucab/consorcio2-petromiles
        skip_cleanup: "true"
      after_deploy:
        - echo "after"
      # - name: Frontend | Vue
      #   install:
      #     - cd petromiles-frontend
      #     - npm install
      #   script:
      #     - npm run build
