language: node_js
node_js:
  - 12.16.2
addons:
  sshknownhosts:
    - 134.122.113.181
branches:
  only:
    - FASE3-028
    - develop
    - master
before_install:
  - echo "$SSH_KEY" > "temp"
  - chmod 600 temp && mv temp ~/.ssh/id_rsa
jobs:
  include:
    - name: Backend | NestJS
      install:
        - cd petromiles-backend
        - npm install
      script:
        - npm run test
        - npm run build
    - name: Frontend | Vue
      install:
        - cd petromiles-frontend
        - npm install
      script:
        - npm run test
        - npm run build
