language: node_js
node_js:
  - 12.16.2
branches:
  only:
    - master
    - develop
    - FASE3-028
jobs:
  include:
    - name: Backend | NestJS
      install:
        - cd petromiles-backend
        - npm install
      script:
        - npm run test
        - npm run test:e2e
        - npm run build
        # Coveralls.io
        # - npm run test:cov
      deploy:
        provider: heroku
        api_key:
          FASE3-028:
            secure: hifh1WGMuZwTnat67PW2KEzE0cV/uD/xXNpZW8ZH6TVcRiRv1bfFu6PeiXnnp5MKRdTbfXotTKYpVMbQk0cKXZkXEjOaQujwgEFqaI3TNZVhz7hlUbs7TwcXxFjvT8jWnGtVzYD8eWc5kwIt3CjdSywK2LCBV+f4MIHw0fPDE6NHdUlMhHMEW8rvds0/xm0VAwC314DcYsZ/tIOwZIPZjOC0LRGWchy9nYqbz7CzEPOUVjTKZSmLkwbGlEqIb9slJ18eD3YSHfCeU8xqXgvrZbhBLsVM3Tbtem+fdyVpeavS01gbKWTN56AdrNnSUYj66j6+IWTgdo8cW0NXI6xZte4h5luyyPvu3Ys34gmwiT+qPaXImNLL28HzzA/uXSZcIozgRwkxUZAe3Wffokyi2pb3A6MOflWF7RWPD8RThudAu7sJPtaUzenAcbLV9K1dwfPwDD5i5DnFJtMIWoh0jY5hP7TMebL3exfT8ZI+HjGK5nOLl6Qj2b15jZgEuT5UiQA0/RfH3JDs7L1xpMXPcNTNncDDxoEiTKpxkH5cEyMN3FliD14srsszIFgDl8i/P+90JoACC6WzDDSzV6tIG017cs0yJXbnevKJP8OSkx0iUE4XNMgPtVuP0qAurjqzYETexwI8XZnjV1vftKZjSKsRrT7b9d2Lxtmv+fVMYy0=
          develop:
            secure: $HEROKU_APIKEY_B
          master:
            secure: $HEROKU_APIKEY_A
        app:
          FASE3-028: prepro-petromiles-backend
          develop: staging-petromiles-backend
          master: prepro-petromiles-backend
        on:
          repo: ingswucab/consorcio2-petromiles
        skip_cleanup: "true"
      after_deploy:
        - echo "after"
      # - name: Frontend | Vue
      #   install:
      #     - cd petromiles-frontend
      #     - npm install
      #   script:
      #     - npm run build
