version: "3"
services:
  # VUE FRONTEND
  frontend:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - .:/app
