enum ApiModules {
  AUTH = 'AUTH',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  CLIENT = 'CLIENT',
  CRON = 'CRON',
  EXAMPLE = 'EXAMPLE',
  LANGUAGE = 'LANGUAGE',
  PAYMENT_PROVIDER = 'PAYMENT_PROVIDER',
  SUSCRIPTION = 'SUSCRIPTION',
  MANAGEMENT = 'MANAGEMENT',
  TRANSACTION = 'TRANSACTION',
  MAILS = 'MAILS',
  USER = 'USER',
  PAYMENTS = 'PAYMENTS',
  THIRD_PARTY_CLIENTS = 'THIRD_PARTY_CLIENTS',
}

enum ApiSubmodules {
  STRIPE = 'STRIPE',
  POEDITOR = 'POEDITOR',
}

export { ApiModules, ApiSubmodules };
