export enum StateName {
  VERIFYING = 'VERIFYING',
  ACTIVE = 'ACTIVE',
  BLOCKED = 'BLOCKED',
  CANCELLED = 'CANCELLED',
  VALID = 'VALID',
  INVALID = 'INVALID',
}

export enum StateType {
  USER = 'USER',
  TRANSACTION = 'TRANSACTION',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
}

export enum StateDescription {
  NEWLY_CREATED_ACCOUNT = 'NEWLY_CREATED_ACCOUNT',
  VERIFICATION_TRANSACTION_CREATION = 'VERIFICATION_TRANSACTION_CREATION',
}
