export enum Bank {
  BANK_OF_AMERICA = 'Bank of America',
  ALLY_BANK = 'Ally Bank',
  BBT_BANK = 'BB&T Bank',
  BBVA_COMPASS = 'BBVA Compass',
  CAPITAL_ONE_BANK = 'Capital One Bank',
  CITIBANK = 'Citibank',
  CITIZENS_BANK = 'Citizens Bank',
  FIFTH_THIRD_BANK = 'Fifth Third Bank',
  WELLS_FARGO_BANK = 'Wells Fargo Bank',
  US_BANK = 'US Bank',
  USAA = 'USAA',
  HSBC_BANK_USA = 'HSBC Bank USA',
  JP_MORGAN_CHASE_BANK = 'J.P. Morgan Chase Bank',
  KEYBANK = 'KeyBank',
  KINETIC_CREDIT_UNION = 'Kinetic Credit Union',
  NAVY_FEDERAL_CREDIT_UNION = 'Navy Federal Credit Union',
  PNC_BANK = 'PNC Bank',
  REGIONS_BANK = 'Regions Bank',
  SUNTRUST_BANK = 'SunTrust Bank',
  TD_BANK = 'TD Bank',
}
