export enum MailsSubject {
  WELCOME = 'Welcome To PetroMiles',
  INVOICE_EN = 'Your transaction is being processed',
  INVOICE_ES = 'Su transacción está siendo procesada',
  UPGRADE_TO_GOLD_EN = 'Thank you for your loyalty!',
  UPGRADE_TO_GOLD_ES = 'Gracias por su lealtad!',
  BANK_A_REGISTRATION_EN = 'Bank Account Registration',
  BANK_A_REGISTRATION_ES = 'Registro de Cuenta Bancaria',
  BANK_A_VERIFIED_EN = 'Bank Account Verification',
  BANK_A_VERIFIED_ES = 'Verificación de Cuenta Bancaria',
  BANK_A_UNVERIFIED_EN = 'Unverified bank account',
  BANK_A_UNVERIFIED_ES = 'Sin verificar cuenta de banco',
  BANK_A_DELETION_EN = 'Bank account deleted',
  BANK_A_DELETION_ES = 'Se elimino la cuenta bancaria',
}

export enum MailsTemplate {
  INVOICE_EN = 'invoice[english]',
  INVOICE_ES = 'invoice[spanish]',
  UPGRADE_TO_GOLD_EN = 'upgradeToGold[english]',
  UPGRADE_TO_GOLD_ES = 'upgradeToGold[spanish]',
  BANK_A_REGISTRATION_EN = 'bankARegistration[english]',
  BANK_A_REGISTRATION_ES = 'bankARegistration[spanish]',
  BANK_A_VERIFIED_EN = 'bankAVerified[english]',
  BANK_A_VERIFIED_ES = 'bankAVerified[spanish]',
  BANK_A_UNVERIFIED_EN = 'bankAUnverified[english]',
  BANK_A_UNVERIFIED_ES = 'bankAUnverified[spanish]',
  BANK_A_DELETION_EN = 'bankADeletion[english]',
  BANK_A_DELETION_ES = 'bankADeletion[spanish]',
}
