export enum StateName {
  VERIFYING = 'verifying',
  ACTIVE = 'active',
  BLOCKED = 'blocked',
  CANCELLED = 'cancelled',
  VALID = 'valid',
  INVALID = 'invalid',
}

export enum StateType {
  USER = 'USER',
  TRANSACTION = 'TRANSACTION',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
}

export enum StateDescription {
  NEWLY_CREATED_ACCOUNT = 'NEWLY_CREATED_ACCOUNT',
  BANK_ACCOUNT_VALIDATION = 'BANK_ACCOUNT_VALIDATION',
  VERIFICATION_TRANSACTION_CREATION = 'VERIFICATION_TRANSACTION_CREATION',
  BANK_ACCOUNT_CANCELLED = 'BANK_ACCOUNT_CANCELLED',
  SUSCRIPTION_UPGRADE = 'SUSCRIPTION_UPGRADE',
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  BANK_ACCOUNT_BLOCKED = 'BANK_ACCOUNT_BLOCKED',
  BANK_ACCOUNT_ACTIVATED = 'BANK_ACCOUNT_ACTIVATED',
}
