export enum StateName {
  VERIFYING = 'verifying',
  ACTIVE = 'active',
  BLOCKED = 'blocked',
  CANCELLED = 'cancelled',
  VALID = 'valid',
  INVALID = 'invalid',
}

export enum StateType {
  USER = 'USER',
  TRANSACTION = 'TRANSACTION',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
}

export enum StateDescription {
  NEWLY_CREATED_ACCOUNT = 'NEWLY_CREATED_ACCOUNT',
  BANK_ACCOUNT_VALIDATION = 'BANK_ACCOUNT_VALIDATION',
  VERIFICATION_TRANSACTION_CREATION = 'VERIFICATION_TRANSACTION_CREATION',
  CHANGE_VERIFICATION_TO_VALID = 'CHANGE_VERIFICATION_TO_VALID',
  NO_ACCOUNT = 'NO_ACCOUNT',
  ACCOUNT_CLOSED = 'ACCOUNT_CLOSED',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  DEBIT_NOT_AUTHORIZED = 'DEBIT_NOT_AUTHORIZED',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  BANK_ACCOUNT_CANCELLED = 'BANK_ACCOUNT_CANCELLED',
  SUSCRIPTION_UPGRADE = 'SUSCRIPTION_UPGRADE',
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  BANK_ACCOUNT_BLOCKED = 'BANK_ACCOUNT_BLOCKED',
  BANK_ACCOUNT_ACTIVATED = 'BANK_ACCOUNT_ACTIVATED',
  THIRD_PARTY_CLIENT_TRANSACTION = 'THIRD_PARTY_CLIENT_TRANSACTION',
}
